package com.nexuschat.app.services

import android.util.Log
import kotlinx.coroutines.*
import java.security.SecureRandom

class CoverTrafficScheduler private constructor() {
    companion object {
        private const val TAG = "NexusChat/CoverTraffic"
        private const val DEFAULT_INTERVAL_MS = 3000L
        private const val MIN_INTERVAL_MS = 500L
        private const val MAX_INTERVAL_MS = 15000L
        @Volatile private var instance: CoverTrafficScheduler? = null
        fun getInstance(): CoverTrafficScheduler =
            instance ?: synchronized(this) {
                instance ?: CoverTrafficScheduler().also { instance = it }
            }
    }

    data class CoverTrafficConfig(
        val enabled: Boolean = true,
        val intervalMs: Long = DEFAULT_INTERVAL_MS,
        val minCellSize: Int = 128,
        val maxCellSize: Int = 1500,
        val burstMode: Boolean = false,
        val burstSize: Int = 3,
        val mimicProtocols: List<String> = listOf("HTTPS", "DNS", "QUIC"),
        val probabilityOfTraffic: Float = 0.3f
    )

    enum class MimicProtocol { HTTPS, DNS, QUIC, NTP, HTTP_2 }

    private val scope = CoroutineScope(Dispatchers.IO + SupervisorJob())
    private val rng = SecureRandom()
    private var config = CoverTrafficConfig()
    private var job: Job? = null
    private var packetsGenerated = 0L
    private var totalBytesGenerated = 0L
    private var onDummyPacket: ((ByteArray) -> Unit)? = null

    data class CoverPacket(
        val data: ByteArray,
        val protocol: MimicProtocol,
        val timestamp: Long,
        val size: Int
    )

    val stats: Pair<Long, Long> get() = Pair(packetsGenerated, totalBytesGenerated)

    fun configure(cfg: CoverTrafficConfig) {
        config = cfg
        Log.i(TAG, "Cover traffic configured: interval=${cfg.intervalMs}ms enabled=${cfg.enabled}")
    }

    fun setPacketHandler(handler: (ByteArray) -> Unit) {
        onDummyPacket = handler
    }

    fun start() {
        if (job != null) return
        job = scope.launch {
            while (true) {
                if (config.enabled && rng.nextFloat() < config.probabilityOfTraffic) {
                    generateAndSendCoverTraffic()
                }
                val jitter = (rng.nextLong() and Long.MAX_VALUE) % config.intervalMs
                delay(config.intervalMs + jitter)
            }
        }
        Log.i(TAG, "Cover traffic scheduler started")
    }

    fun stop() {
        job?.cancel()
        job = null
        Log.i(TAG, "Cover traffic scheduler stopped: $packetsGenerated packets, $totalBytesGenerated bytes")
    }

    suspend fun generateCoverPacket(): CoverPacket = withContext(Dispatchers.Default) {
        val protocol = MimicProtocol.values()[rng.nextInt(MimicProtocol.values().size)]
        val cellSize = if (protocol == MimicProtocol.DNS) rng.nextInt(128) + 40
            else if (protocol == MimicProtocol.NTP) 48
            else rng.nextInt(config.maxCellSize - config.minCellSize) + config.minCellSize
        val data = ByteArray(cellSize)
        when (protocol) {
            MimicProtocol.HTTPS -> {
                data[0] = 0x47; data[1] = 0x45; data[2] = 0x54; data[3] = 0x20
                val path = "/${rng.nextInt(9999)}"
                System.arraycopy(path.toByteArray(), 0, data, 4, kotlin.math.min(path.length, cellSize - 4))
                data[cellSize - 2] = 0x0D; data[cellSize - 1] = 0x0A
            }
            MimicProtocol.DNS -> {
                val id = rng.nextInt(65535)
                data[0] = (id shr 8).toByte(); data[1] = id.toByte()
                data[2] = 0x01; data[3] = 0x20
                data[4] = 0x00; data[5] = 0x01
                val tail = ByteArray(cellSize - 12); rng.nextBytes(tail); System.arraycopy(tail, 0, data, 12, tail.size)
            }
            MimicProtocol.QUIC -> {
                data[0] = (0xC0 or rng.nextInt(0x3F)).toByte()
                data[1] = rng.nextInt(255).toByte()
                val dcId = rng.nextLong()
                for (i in 0..7) data[2 + i] = (dcId shr (i * 8)).toByte()
            }
            MimicProtocol.NTP -> {
                data[0] = 0x1B; data[1] = 0x00; data[2] = 0x00; data[3] = 0x00
                val ts = System.currentTimeMillis() / 1000L + 2208988800L
                for (i in 0..3) data[40 + i] = (ts shr ((3 - i) * 8)).toByte()
            }
            MimicProtocol.HTTP_2 -> {
                data[0] = 0x50; data[1] = 0x52; data[2] = 0x49; data[3] = 0x20
                data[4] = (rng.nextInt(255) and 0xFC).toByte()
                data[5] = rng.nextInt(255).toByte()
                data[6] = rng.nextInt(255).toByte()
                data[7] = rng.nextInt(255).toByte()
                for (i in 0 until minOf(8, cellSize - 9)) {
                    data[9 + i] = ('a'.code + rng.nextInt(26)).toByte()
                }
            }
        }
        CoverPacket(data, protocol, System.currentTimeMillis(), data.size)
    }

    private fun minOf(a: Int, b: Int) = if (a < b) a else b

    private suspend fun generateAndSendCoverTraffic() {
        try {
            val packet = generateCoverPacket()
            onDummyPacket?.invoke(packet.data)
            packetsGenerated++
            totalBytesGenerated += packet.data.size
            if (packetsGenerated % 100 == 0L) {
                Log.d(TAG, "Cover traffic: $packetsGenerated packets, ${totalBytesGenerated / 1024} KB")
            }
            if (config.burstMode) {
                repeat(config.burstSize - 1) {
                    val burstPacket = generateCoverPacket()
                    onDummyPacket?.invoke(burstPacket.data)
                    packetsGenerated++
                    totalBytesGenerated += burstPacket.data.size
                    delay((rng.nextLong() and Long.MAX_VALUE) % 100)
                }
            }
        } catch (e: Exception) {
            Log.w(TAG, "Cover traffic generation failed: ${e.message}")
        }
    }

    fun destroy() {
        stop()
        scope.cancel()
        instance = null
    }
}
