#!/bin/bash
# startup-report.sh — после перезагрузки собирает полный отчёт + логи и отправляет Инквизитору
# Вызывается из post-reboot-restore.sh после того, как сервер полностью загружен.
set -euo pipefail

DATA_DIR="${HOME}/.local/share/ParanoidX"
REPORT_FILE="/tmp/startup-report-$(date +%Y%m%d-%H%M%S).md"

# Ждём, пока API станет доступен (максимум 60 сек)
wait_for_api() {
  local max_attempts=30
  local attempt=0
  while [ $attempt -lt $max_attempts ]; do
    if curl -sf --max-time 2 http://127.0.0.1:8080/api/health >/dev/null 2>&1; then
      return 0
    fi
    sleep 2
    attempt=$((attempt + 1))
  done
  return 1
}

collect_report() {
  local f="$1"

  # Заголовок
  {
    echo "# 🏁 Startup Report — $(date '+%Y-%m-%d %H:%M:%S %Z')"
    echo ""
    echo "**Host:** $(hostname)"
    echo "**Kernel:** $(uname -r)"
    echo "**Uptime:** $(uptime -p)"
    echo "**Load:** $(uptime | awk -F'load average:' '{print $2}')"
    echo ""
  } > "$f"

  # 1. Версия и аптайм сервера
  {
    echo "## 1. Server Status"
    echo '```json'
    curl -sf http://127.0.0.1:8080/api/version 2>/dev/null || echo '{"error":"unreachable"}'
    echo '```'
    echo ""
    echo '**Health:**'
    echo '```json'
    curl -sf http://127.0.0.1:8080/api/health 2>/dev/null || echo '{"error":"unreachable"}'
    echo '```'
    echo ""
  } >> "$f"

  # 2. Docker контейнеры
  {
    echo "## 2. Docker Containers"
    echo '```'
    docker ps -a --format 'table {{.Names}}\t{{.State}}\t{{.Status}}' 2>/dev/null || echo "Docker not available"
    echo '```'
    echo ""
  } >> "$f"

  # 3. DC CryptoCloud
  {
    echo "## 3. DC CryptoCloud"
    echo '```json'
    curl -sf http://127.0.0.1:8080/api/dc/status 2>/dev/null || echo '{"error":"unreachable"}'
    echo '```'
    echo ""
  } >> "$f"

  # 4. Silver Oracle
  {
    echo "## 4. Silver Oracle"
    echo '```'
    cat "$DATA_DIR/silver_spot_usd.txt" 2>/dev/null || echo "N/A"
    echo '```'
    echo ""
  } >> "$f"

  # 5. Chat Bridge
  {
    echo "## 5. Chat Bridge"
    echo '```json'
    curl -sf http://127.0.0.1:8080/api/chat/status 2>/dev/null || echo '{"error":"unreachable"}'
    echo '```'
    echo ""
  } >> "$f"

  # 6. Диск
  {
    echo "## 6. Disk Usage"
    echo '```'
    df -h "$DATA_DIR" 2>/dev/null | tail -1
    du -sh "$DATA_DIR" 2>/dev/null
    echo '```'
    echo ""
  } >> "$f"

  # 7. System Memory
  {
    echo "## 7. System Resources"
    echo '```'
    free -h 2>/dev/null | tail -2
    echo '```'
    echo ""
  } >> "$f"

  # 8. Последние 60 строк лога сервера
  {
    echo "## 8. Recent Server Log (last 60 lines)"
    echo '```'
    tail -60 "$DATA_DIR/logs/dashboard.log" 2>/dev/null || echo "Log not found"
    echo '```'
    echo ""
  } >> "$f"

  # 9. Docker compose logs (smp, xftp, tor — последние 20 строк каждого)
  {
    echo "## 9. Docker Service Logs (last 20 lines each)"
    for svc in tor smp-server xftp-server v2ray coturn; do
      echo "### $svc"
      echo '```'
      docker logs --tail 20 "ParanoidX-$svc" 2>/dev/null || echo "Container not found"
      echo '```'
      echo ""
    done
  } >> "$f"

  # 10. SOS — список ошибок/варнингов в логах
  {
    echo "## 10. Error/Warning Summary (last 100 lines)"
    echo '```'
    tail -100 "$DATA_DIR/logs/dashboard.log" 2>/dev/null | grep -iE 'error|warn|fail|panic|critical|denied' | tail -20 || echo "No errors found"
    echo '```'
    echo ""
  } >> "$f"

  echo "_Report generated by startup-report.sh_" >> "$f"
}

# Главная
if ! wait_for_api; then
  echo "ERROR: API not available after 60s" >&2
  # Всё равно шлём что есть
fi

collect_report "$REPORT_FILE"

# Отправляем как документ
bash "$(dirname "$0")/send-to-inquisitor.sh" -d "$REPORT_FILE" \
  "🏁 Startup Report — $(date '+%Y-%m-%d %H:%M') | $(uptime -p)"

rm -f "$REPORT_FILE"
echo "Startup report sent to Inquisitor"
