org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.java.home=/home/thomas/.sdkman/candidates/java/21.0.4-tem

android.useAndroidX=true
android.enableJetifier=true
android.nonTransitiveRClass=true

kotlin.code.style=official
